### ISSUE TITLE
How to hide the logbook name?

### ISSUE THREAD

**Issue by mstuij** [royto/logbook-card#82]
I'm using the multiple entities (thanks for adding it!).

But is it possible to hide the logbook name? So for example: 

"Automation covers log" 
"Automation lights log"

![image](https://github.com/royto/logbook-card/assets/75884924/7b77a8a8-6e8c-4aa7-881d-e6776f559082)

```
type: custom:multiple-logbook-card
entities:
  - entity: input_button.automation_log_entity
    custom_logs: true
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
      title: test
    hidden_state:
      - unknown
  - entity: input_button.automation_covers_log_entity
    custom_logs: true
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
    hidden_state:
      - unknown
  - entity: input_button.automation_lights_log_entity
    custom_logs: true
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
    hidden_state:
      - unknown
  - entity: input_button.automation_washingmachine_log_entity
    custom_logs: true
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
    hidden_state:
      - unknown
  - entity: input_button.automation_dryer_log_entity
    custom_logs: true
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
    hidden_state:
      - unknown
title: Automatiseringen logboek
history: 7
date_format: ddd DD-MM-YYYY HH:mm:ss
scroll: false

```

**Comment by royto** [comment]
Fixed in [2.0.1](https://github.com/royto/logbook-card/releases/tag/2.0.1)

For your information, from 2.0.0, you can now remove hidden_state and set show_history to false.

For example you can use:

```yaml
type: custom:multiple-logbook-card
entities:  
  - entity: input_button.automation_dryer_log_entity
    custom_logs: true
    show_history: false
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
    
```

**Comment by mstuij** [comment]
It doesn't seems to be working. You still see the dummy entity log name:


![image](https://github.com/royto/logbook-card/assets/75884924/161a8fea-8b83-4211-abd9-a4ea529a297f)


```
type: custom:multiple-logbook-card
entities:
  - entity: input_button.automation_log_entity
    custom_logs: true
    show_history: false
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
      entity_name: false
  - entity: input_button.automation_covers_log_entity
    custom_logs: true
    show_history: false
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
      entity_name: false
  - entity: input_button.automation_lights_log_entity
    custom_logs: true
    show_history: false
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
      entity_name: false
  - entity: input_button.automation_washingmachine_log_entity
    custom_logs: true
    show_history: false
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
      entity_name: false
  - entity: input_button.automation_dryer_log_entity
    custom_logs: true
    show_history: false
    show:
      state: true
      duration: false
      start_date: true
      end_date: false
      icon: true
      separator: true
      entity_name: false
title: Automatiseringen logboek
history: 7
date_format: ddd DD-MM-YYYY HH:mm:ss
scroll: false

```

**Comment by royto** [comment]
Find the pb. 
The [show](https://github.com/royto/logbook-card/#available-show-options) option is on the root of the config and not for each entity

This configuration should work

```yaml
type: custom:multiple-logbook-card
entities:
  - entity: input_button.automation_log_entity
    custom_logs: true
    show_history: false
  - entity: input_button.automation_covers_log_entity
    custom_logs: true
    show_history: false
  - entity: input_button.automation_lights_log_entity
    custom_logs: true
    show_history: false
  - entity: input_button.automation_washingmachine_log_entity
    custom_logs: true
    show_history: false
  - entity: input_button.automation_dryer_log_entity
    custom_logs: true
    show_history: false
show:
   state: true
   duration: false
   start_date: true
   end_date: false
   icon: true
   separator: true
   entity_name: false
title: Automatiseringen logboek
history: 7
date_format: ddd DD-MM-YYYY HH:mm:ss
scroll: false
```

**Comment by mstuij** [comment]
Thanks that solved the issue.
